"""Init ProjectSpecificCriterion table

Revision ID: 1eb73cb5382e
Revises: 59553a75872c
Create Date: 2021-10-25 15:06:17.195592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eb73cb5382e'
down_revision = '59553a75872c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_specific_criterion',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('project_criterion_id', sa.Integer(), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.CheckConstraint('1 <= project_specific_criterion.project_id', name='ck_project_specific_criterion_project_id'),
    sa.ForeignKeyConstraint(['project_criterion_id'], ['project_criterion.project_criterion_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'project_criterion_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_specific_criterion')
    # ### end Alembic commands ###
