"""Init ProjectCriterion table

Revision ID: 59553a75872c
Revises: 496e116f6c78
Create Date: 2021-10-21 16:03:36.940094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59553a75872c'
down_revision = '496e116f6c78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_criterion',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('project_criterion_id', sa.Integer(), server_default=sa.text("nextval('mado_seq')"), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('max_value', sa.Integer(), nullable=False),
    sa.Column('normal_threshold', sa.Integer(), nullable=False),
    sa.CheckConstraint('1 <= project_criterion.max_value', name='ck_project_criterion_max_value'),
    sa.CheckConstraint('1 <= project_criterion.normal_threshold AND project_criterion.normal_threshold <= max_value', name='ck_project_criterion_normal_threshold'),
    sa.PrimaryKeyConstraint('project_criterion_id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_criterion')
    # ### end Alembic commands ###
