"""Init ProjectCriterionValue table

Revision ID: ad8e8fd9ca31
Revises: c619ba1873b0
Create Date: 2021-10-28 17:49:07.538705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad8e8fd9ca31'
down_revision = 'c619ba1873b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_criterion_value',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('project_criterion_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('1 <= project_criterion_value.value', name='ck_project_criterion_value_value'),
    sa.CheckConstraint('project_criterion_value.author_id IS NULL OR 1 <= project_criterion_value.author_id',
                       name='ck_project_criterion_value_author_id'),
    sa.ForeignKeyConstraint(['project_id', 'project_criterion_id'],
                            ['project_specific_criterion.project_id', 'project_specific_criterion.project_criterion_id'],
                            ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'project_criterion_id', 'date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_criterion_value')
    # ### end Alembic commands ###
