"""Init ProjectStatus table

Revision ID: c619ba1873b0
Revises: 1eb73cb5382e
Create Date: 2021-10-28 17:16:18.901754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c619ba1873b0'
down_revision = '1eb73cb5382e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_status',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('project_status_id', sa.Integer(), server_default=sa.text("nextval('mado_seq')"), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('aggregated_value', sa.Integer(), nullable=False),
    sa.Column('latest_updated_at', sa.Date(), nullable=False),
    sa.Column('latest_updater_id', sa.Integer(), nullable=False),
    sa.Column('latest_grades', sa.JSON(), nullable=False),
    sa.CheckConstraint('1 <= project_status.project_id', name='ck_project_status_project_id'),
    sa.PrimaryKeyConstraint('project_status_id'),
    sa.UniqueConstraint('project_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_status')
    # ### end Alembic commands ###
